In [1]:
import os
if os.getenv("CUDA_VISIBLE_DEVICES") is None:
    gpu_num = 0 # Use "" to use the CPU
    os.environ["CUDA_VISIBLE_DEVICES"] = f"{gpu_num}"
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
# tahtan
# Import Sionna
import sys
sys.path.append('../')
import sionna

# try:
#     import sionna
# except ImportError as e:
#     # Install Sionna if package is not already installed
#     import os
#     os.system("pip install sionna")
#     import sionna

import tensorflow as tf
# Configure the notebook to use only a single GPU and allocate only as much memory as needed
# For more details, see https://www.tensorflow.org/guide/gpu
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        tf.config.experimental.set_memory_growth(gpus[0], True)
    except RuntimeError as e:
        print(e)
# Avoid warnings from TensorFlow
tf.get_logger().setLevel('ERROR')

sionna.config.seed = 42 # Set seed for reproducible results

# Load the required Sionna components
from sionna.nr import PUSCHConfig, PUSCHTransmitter, PUSCHReceiver, CarrierConfig, PUSCHDMRSConfig,\
                        TBConfig, PUSCHPilotPattern, TBEncoder, PUSCHPrecoder, LayerMapper, LayerDemapper, check_pusch_configs,\
                        TBDecoder, PUSCHLSChannelEstimator
from sionna.nr.utils import generate_prng_seq
from sionna.channel import AWGN, RayleighBlockFading, OFDMChannel, TimeChannel, time_lag_discrete_time_channel
from sionna.channel.utils import * 
from sionna.channel.tr38901 import Antenna, AntennaArray, UMi, UMa, RMa, TDL, CDL
from sionna.channel import gen_single_sector_topology as gen_topology
from sionna.utils import compute_ber, ebnodb2no, sim_ber, array_to_hash, create_timestamped_folders, b2b, f2f, BinarySource
from sionna.ofdm import KBestDetector, LinearDetector, MaximumLikelihoodDetector,\
        LSChannelEstimator, LMMSEEqualizer, RemoveNulledSubcarriers, ResourceGridDemapper,\
        ResourceGrid, ResourceGridMapper, OFDMModulator
from sionna.mimo import StreamManagement
from sionna.mapping import Mapper, Demapper

from sionna.nr.my_abc import *

ImportError: cannot import name 'Model' from 'tensorflow.keras.layers' (/workspaces/thanh/.venv/lib/python3.11/site-packages/keras/api/_v2/keras/layers/__init__.py)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import time
from datetime import datetime, timedelta
# from bs4 import BeautifulSoup
import pickle
from collections import namedtuple
import json
from tqdm.notebook import tqdm
import itertools
import io
import h5py

## A Hello World Example

Let us start with a simple "Hello, World!" example in which we will simulate PUSCH transmissions from a single transmitter to a single receiver over an AWGN channel.

In [ ]:
def data_loader(df, dir, saved_dataset='hdf5'):
    assert saved_dataset in ['hdf5', 'pickle'], "saved data set should be 'pickle' or 'hdf5'."
    assert df['nTBSize'].nunique() == 1, "Not all elements have the same TB size."
    assert df['Dmrs_mask'].map(len).nunique() == 1, "Not all elements have the same number of Dmrs/Data symbols."
    for pusch_record in df.itertuples():
        data_filename = pusch_record.Data_filename
        data_dirname = pusch_record.Data_dirname
        esno_db = pusch_record.Esno_db
        index = pusch_record.Index
        data_mask = ~pusch_record.Dmrs_mask
        if saved_dataset == 'hdf5':
            b,c,y = load_hdf5(f'{dir}/{data_dirname}', data_filename)
        else:
            b,c,y = load_pickle(f'{dir}/{data_dirname}', data_filename)
        data_ind = tf.where(
            tf.repeat(
                data_mask.reshape(y.shape[-2],y.shape[-1],1),
                len(c)/np.sum(data_mask, axis=-1),
                axis=2)
            )
        yield index, esno_db, c, y, b, data_ind

def preprocessing(index, esno_db, c, y, b, data_ind):
    
    return index, esno_db, c, y, b, data_ind

dataset_dir = f'../Pusch_data/dataset'
pickles_dir = f'{dataset_dir}/pickle'
hdf5_dir = f'{dataset_dir}/hdf5'
parquet_dir = f'{dataset_dir}/parquet'

# parquet_name = 20250306015239576970
parquet_name = 20250306015626321031

In [44]:
df = pd.read_parquet(f'{parquet_dir}/{parquet_name}.parquet', engine="pyarrow")

In [ ]:
cfg_cols = ['nPhyCellId', 'nCpType', 'nSubcSpacing', 'nBWPSize', 'nBWPStart', 'nSlot',
'nDMRSConfigType', 'nNrOfDMRSSymbols', 'nDMRSAddPos', 'nPortIndex', 'nNIDnSCID', 'nSCID', 'nNrOfCDMs', 'nDMRSTypeAPos',
'nNid', 'nMcsTable', 'nMCS',
'nMappingType', 'nNrOfLayers', 'nTransmissionScheme', 'nPMI', 'nTransPrecode', 'nRNTI',
'nStartSymbolIndex', 'nNrOfSymbols', 'nRBStart', 'nRBSize',
'nPTRSPresent', 'nAck', 'nCsiPart1', 'nCsiPart2', 'nTpPi2BPSK']

In [59]:
df_copy = df[cfg_cols].copy()
for col in df_copy.columns:
    if isinstance(df_copy[col].iloc[0], np.ndarray):  # Check first element type
        df_copy[col] = df_copy[col].apply(lambda x: tuple(x) if isinstance(x, np.ndarray) else x)
df_drop_dup = df_copy.drop_duplicates()
df_drop_dup

,nPhyCellId,nCpType,nSubcSpacing,nBWPSize,nBWPStart,nSlot,nDMRSConfigType,nNrOfDMRSSymbols,nDMRSAddPos,nPortIndex,...,nRNTI,nStartSymbolIndex,nNrOfSymbols,nRBStart,nRBSize,nPTRSPresent,nAck,nCsiPart1,nCsiPart2,nTpPi2BPSK
0,246,0,1,273,0,4,0,1,1,"(0,)",...,20004,0,14,0,273,0,0,0,0,0

In [60]:
grouped_indices = df_copy.reset_index().groupby(list(df_copy.columns)).agg(indices=('index',list)).reset_index()
grouped_indices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   nPhyCellId           1 non-null      int64
 1   nCpType              1 non-null      int64
 2   nSubcSpacing         1 non-null      int64
 3   nBWPSize             1 non-null      int64
 4   nBWPStart            1 non-null      int64
 5   nSlot                1 non-null      int64
 6   nDMRSConfigType      1 non-null      int64
 7   nNrOfDMRSSymbols     1 non-null      int64
 8   nDMRSAddPos          1 non-null      int64
 9   nPortIndex           1 non-null      object
 10  nNIDnSCID            1 non-null      int64
 11  nSCID                1 non-null      int64
 12  nNrOfCDMs            1 non-null      int64
 13  nDMRSTypeAPos        1 non-null      int64
 14  nNid                 1 non-null      int64
 15  nMcsTable            1 non-null      int64
 16  nMCS                 1 non-null      int64
 17  nMappingType         1 non-null      int64
 18  nNrOfLayers          1 non-null      int64
 19  nTransmissionScheme  1 non-null      int64
 20  nPMI                 1 non-null      int64
 21  nTransPrecode        1 non-null      int64
 22  nRNTI                1 non-null      int64
 23  nStartSymbolIndex    1 non-null      int64
 24  nNrOfSymbols         1 non-null      int64
 25  nRBStart             1 non-null      int64
 26  nRBSize              1 non-null      int64
 27  nPTRSPresent         1 non-null      int64
 28  nAck                 1 non-null      int64
 29  nCsiPart1            1 non-null      int64
 30  nCsiPart2            1 non-null      int64
 31  nTpPi2BPSK           1 non-null      int64
 32  indices              1 non-null      object
dtypes: int64(31), object(2)
memory usage: 396.0+ bytes

In [61]:
grouped_indices

,nPhyCellId,nCpType,nSubcSpacing,nBWPSize,nBWPStart,nSlot,nDMRSConfigType,nNrOfDMRSSymbols,nDMRSAddPos,nPortIndex,...,nStartSymbolIndex,nNrOfSymbols,nRBStart,nRBSize,nPTRSPresent,nAck,nCsiPart1,nCsiPart2,nTpPi2BPSK,indices
0,246,0,1,273,0,4,0,1,1,"(0,)",...,0,14,0,273,0,0,0,0,0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,..."

In [57]:
def create_configs_from_df(grouped_df: pd.DataFrame) -> List[MyConfig]:
    configs_and_indices = []
    
    for row in grouped_df.itertuples():
        sys_cfg = SystemConfig(
            NCellId=row.nPhyCellId if hasattr(row, 'nPhyCellId') else row.nNid,
            CpType=row.nCpType,
            NTxAnt=1,  # Keeping it constant as in the default
            NRxAnt=8,  # Keeping it constant as in the default
            BwpNRb=row.nBWPSize,
            BwpRbOffset=row.nBWPStart
        )

        ue_cfg = UeConfig(
            TransformPrecoding=row.nTransPrecode,
            Rnti=row.nRNTI,
            nId=row.nNid,
            NLayers=row.nNrOfLayers,
            FirstSymb=row.nStartSymbolIndex,
            NPuschSymbAll=row.nNrOfSymbols,
            FirstPrb=row.nRBStart,
            NPrb=row.nRBSize,
            McsTable=row.nMcsTable,
            Mcs=row.nMCS,
            nScId=row.nSCID,
            NnScIdId=row.nNIDnSCID,
            DmrsConfigurationType=row.nDMRSConfigType,
            DmrsDuration=row.nNrOfDMRSSymbols,
            DmrsAdditionalPosition=row.nDMRSAddPos,
            PuschMappingType=row.nMappingType,
            DmrsTypeAPosition=row.nDMRSTypeAPos,
            Ptrs=row.nPTRSPresent,
            OAck=row.nAck,
            OCsi1=row.nCsiPart1,
            OCsi2=row.nCsiPart2,
            TpPi2Bpsk=row.nTpPi2BPSK
        )

        my_cfg = MyConfig(Sys=sys_cfg, Ue=[ue_cfg])
        pusch_cfg = MyPUSCHConfig(my_cfg, row.nSlot, row.nSFN)
        configs_and_indices.append((pusch_cfg, row.indices))

    return configs_and_indices

configs_and_indices = create_configs_from_df(grouped_indices)

AttributeError: 'Pandas' object has no attribute 'nPTRSPresent'

In [34]:
dataset_0 = tf.data.Dataset.from_generator(
            lambda: data_loader(df.iloc[configs_and_indices[1][1]], hdf5_dir),
            output_types=(tf.int32, tf.float32, tf.float32, tf.complex64, tf.float32, tf.int32))

In [35]:
for n, (index, esno_db, c, y, b, data_ind) in enumerate(dataset_0.map(preprocessing).batch(2)):
    print(index, n, esno_db.shape, c.shape, y.shape, b.shape, data_ind.shape)

tf.Tensor([ 1 13], shape=(2,), dtype=int32) 0 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([25 37], shape=(2,), dtype=int32) 1 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([49 61], shape=(2,), dtype=int32) 2 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([73 85], shape=(2,), dtype=int32) 3 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([ 97 109], shape=(2,), dtype=int32) 4 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([121 133], shape=(2,), dtype=int32) 5 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([145 157], shape=(2,), dtype=int32) 6 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([169 181], shape=(2,), dtype=int32) 7 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([193 205], shape=(2,), dtype=int32) 8 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([217 229], shape=(2,), dtype=int32) 9 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([241 253], shape=(2,), dtype=int32) 10 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([265 277], shape=(2,), dtype=int32) 11 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([289 301], shape=(2,), dtype=int32) 12 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([313 325], shape=(2,), dtype=int32) 13 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([337 349], shape=(2,), dtype=int32) 14 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([361 373], shape=(2,), dtype=int32) 15 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([385 397], shape=(2,), dtype=int32) 16 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([409 421], shape=(2,), dtype=int32) 17 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([433 445], shape=(2,), dtype=int32) 18 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([457 469], shape=(2,), dtype=int32) 19 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)
tf.Tensor([481 493], shape=(2,), dtype=int32) 20 (2,) (2, 1152) (2, 8, 14, 48) (2, 288) (2, 1152, 3)

In [36]:
ue_antenna = Antenna(polarization="single",
                polarization_type="V",
                antenna_pattern="38.901",
                carrier_frequency=2.55e9)

gnb_array = AntennaArray(num_rows=1,
                        num_cols=8//2,
                        polarization="dual",
                        polarization_type="cross",
                        antenna_pattern="38.901",
                        carrier_frequency=2.55e9)

channel_model = CDL(model = 'C',
                            delay_spread = 150*1e-9,
                            carrier_frequency = 2.55e9,
                            ut_array = ue_antenna,
                            bs_array = gnb_array,
                            direction = 'uplink',
                            min_speed = 10,
                            max_speed = 10)

simulator = MySimulator(configs_and_indices[1][0])

channel = OFDMChannel(channel_model=channel_model, resource_grid=simulator.resource_grid,
                                    add_awgn=False, normalize_channel=True, return_channel=True)

b, c, y = simulator.sim(1, channel, 1.)
print(y.shape)
simulator.rec(y)

(1, 1, 8, 14, 48)

(<tf.Tensor: shape=(1, 1, 288), dtype=float32, numpy=
 array([[[1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0.,
          0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1.,
          0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
          1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0.,
          0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
          0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1.,
          1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1.,
          0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0.,
          1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
          1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0.,
          0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
          1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1.,
          0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1.,
          1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
          0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0.,
          1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1.]]],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 1, 1152), dtype=float32, numpy=
 array([[[[ -8165.2114,   6752.6206,  11472.542 , ...,   8320.597 ,
           -13104.706 , -10258.022 ]]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1), dtype=bool, numpy=array([[ True]])>)

In [37]:
for (config, indices) in configs_and_indices:
    print(indices)

[0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 156, 168, 180, 192, 204, 216, 228, 240, 252, 264, 276, 288, 300, 312, 324, 336, 348, 360, 372, 384, 396, 408, 420, 432, 444, 456, 468, 480, 492]
[1, 13, 25, 37, 49, 61, 73, 85, 97, 109, 121, 133, 145, 157, 169, 181, 193, 205, 217, 229, 241, 253, 265, 277, 289, 301, 313, 325, 337, 349, 361, 373, 385, 397, 409, 421, 433, 445, 457, 469, 481, 493]
[2, 14, 26, 38, 50, 62, 74, 86, 98, 110, 122, 134, 146, 158, 170, 182, 194, 206, 218, 230, 242, 254, 266, 278, 290, 302, 314, 326, 338, 350, 362, 374, 386, 398, 410, 422, 434, 446, 458, 470, 482, 494]
[3, 15, 27, 39, 51, 63, 75, 87, 99, 111, 123, 135, 147, 159, 171, 183, 195, 207, 219, 231, 243, 255, 267, 279, 291, 303, 315, 327, 339, 351, 363, 375, 387, 399, 411, 423, 435, 447, 459, 471, 483, 495]
[4, 16, 28, 40, 52, 64, 76, 88, 100, 112, 124, 136, 148, 160, 172, 184, 196, 208, 220, 232, 244, 256, 268, 280, 292, 304, 316, 328, 340, 352, 364, 376, 388, 400, 412, 424, 436, 448, 460, 472, 484, 496]
[5, 17, 29, 41, 53, 65, 77, 89, 101, 113, 125, 137, 149, 161, 173, 185, 197, 209, 221, 233, 245, 257, 269, 281, 293, 305, 317, 329, 341, 353, 365, 377, 389, 401, 413, 425, 437, 449, 461, 473, 485, 497]
[6, 18, 30, 42, 54, 66, 78, 90, 102, 114, 126, 138, 150, 162, 174, 186, 198, 210, 222, 234, 246, 258, 270, 282, 294, 306, 318, 330, 342, 354, 366, 378, 390, 402, 414, 426, 438, 450, 462, 474, 486, 498]
[7, 19, 31, 43, 55, 67, 79, 91, 103, 115, 127, 139, 151, 163, 175, 187, 199, 211, 223, 235, 247, 259, 271, 283, 295, 307, 319, 331, 343, 355, 367, 379, 391, 403, 415, 427, 439, 451, 463, 475, 487, 499]
[8, 20, 32, 44, 56, 68, 80, 92, 104, 116, 128, 140, 152, 164, 176, 188, 200, 212, 224, 236, 248, 260, 272, 284, 296, 308, 320, 332, 344, 356, 368, 380, 392, 404, 416, 428, 440, 452, 464, 476, 488, 500]
[9, 21, 33, 45, 57, 69, 81, 93, 105, 117, 129, 141, 153, 165, 177, 189, 201, 213, 225, 237, 249, 261, 273, 285, 297, 309, 321, 333, 345, 357, 369, 381, 393, 405, 417, 429, 441, 453, 465, 477, 489, 501]
[10, 22, 34, 46, 58, 70, 82, 94, 106, 118, 130, 142, 154, 166, 178, 190, 202, 214, 226, 238, 250, 262, 274, 286, 298, 310, 322, 334, 346, 358, 370, 382, 394, 406, 418, 430, 442, 454, 466, 478, 490, 502]
[11, 23, 35, 47, 59, 71, 83, 95, 107, 119, 131, 143, 155, 167, 179, 191, 203, 215, 227, 239, 251, 263, 275, 287, 299, 311, 323, 335, 347, 359, 371, 383, 395, 407, 419, 431, 443, 455, 467, 479, 491, 503]

In [38]:
simulator_0 = MySimulator(configs_and_indices[0][0])
for (config, indices) in configs_and_indices[1:2]:
    dataset_0 = tf.data.Dataset.from_generator(
                lambda: data_loader(df.iloc[indices], hdf5_dir),
                output_types=(tf.int32, tf.float32, tf.float32, tf.complex64, tf.float32, tf.int32))
    
    for n, (index, esno_db, c, y, b, data_ind) in enumerate(dataset_0.map(preprocessing).batch(1)):
        _,_, crc = simulator_0.rec(y[:,None])
        print(n, index, crc, esno_db)

0 tf.Tensor([1], shape=(1,), dtype=int32) tf.Tensor([[False]], shape=(1, 1), dtype=bool) tf.Tensor([-5.], shape=(1,), dtype=float32)
1 tf.Tensor([13], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-4.5], shape=(1,), dtype=float32)
2 tf.Tensor([25], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-4.], shape=(1,), dtype=float32)
3 tf.Tensor([37], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-3.5], shape=(1,), dtype=float32)
4 tf.Tensor([49], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-3.], shape=(1,), dtype=float32)
5 tf.Tensor([61], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-2.5], shape=(1,), dtype=float32)
6 tf.Tensor([73], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-2.], shape=(1,), dtype=float32)
7 tf.Tensor([85], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-1.5], shape=(1,), dtype=float32)
8 tf.Tensor([97], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-1.], shape=(1,), dtype=float32)
9 tf.Tensor([109], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-0.5], shape=(1,), dtype=float32)
10 tf.Tensor([121], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([0.], shape=(1,), dtype=float32)
11 tf.Tensor([133], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([0.5], shape=(1,), dtype=float32)
12 tf.Tensor([145], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([1.], shape=(1,), dtype=float32)
13 tf.Tensor([157], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([1.5], shape=(1,), dtype=float32)
14 tf.Tensor([169], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([2.], shape=(1,), dtype=float32)
15 tf.Tensor([181], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([2.5], shape=(1,), dtype=float32)
16 tf.Tensor([193], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([3.], shape=(1,), dtype=float32)
17 tf.Tensor([205], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([3.5], shape=(1,), dtype=float32)
18 tf.Tensor([217], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([4.], shape=(1,), dtype=float32)
19 tf.Tensor([229], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([4.5], shape=(1,), dtype=float32)
20 tf.Tensor([241], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([5.], shape=(1,), dtype=float32)
21 tf.Tensor([253], shape=(1,), dtype=int32) tf.Tensor([[False]], shape=(1, 1), dtype=bool) tf.Tensor([-5.], shape=(1,), dtype=float32)
22 tf.Tensor([265], shape=(1,), dtype=int32) tf.Tensor([[False]], shape=(1, 1), dtype=bool) tf.Tensor([-4.5], shape=(1,), dtype=float32)
23 tf.Tensor([277], shape=(1,), dtype=int32) tf.Tensor([[False]], shape=(1, 1), dtype=bool) tf.Tensor([-4.], shape=(1,), dtype=float32)
24 tf.Tensor([289], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-3.5], shape=(1,), dtype=float32)
25 tf.Tensor([301], shape=(1,), dtype=int32) tf.Tensor([[False]], shape=(1, 1), dtype=bool) tf.Tensor([-3.], shape=(1,), dtype=float32)
26 tf.Tensor([313], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-2.5], shape=(1,), dtype=float32)
27 tf.Tensor([325], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-2.], shape=(1,), dtype=float32)
28 tf.Tensor([337], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-1.5], shape=(1,), dtype=float32)
29 tf.Tensor([349], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-1.], shape=(1,), dtype=float32)
30 tf.Tensor([361], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([-0.5], shape=(1,), dtype=float32)
31 tf.Tensor([373], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([0.], shape=(1,), dtype=float32)
32 tf.Tensor([385], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([0.5], shape=(1,), dtype=float32)
33 tf.Tensor([397], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([1.], shape=(1,), dtype=float32)
34 tf.Tensor([409], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([1.5], shape=(1,), dtype=float32)
35 tf.Tensor([421], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([2.], shape=(1,), dtype=float32)
36 tf.Tensor([433], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([2.5], shape=(1,), dtype=float32)
37 tf.Tensor([445], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([3.], shape=(1,), dtype=float32)
38 tf.Tensor([457], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([3.5], shape=(1,), dtype=float32)
39 tf.Tensor([469], shape=(1,), dtype=int32) tf.Tensor([[ True]], shape=(1, 1), dtype=bool) tf.Tensor([4.], shape=(1,), dtype=float32)

KeyboardInterrupt:

In [ ]:
configs_and_indices[0][1]

In [26]:
for n, (index, esno_db, c, y, b, data_ind) in enumerate(dataset.map(preprocessing).batch(2)):
    print(index, n, esno_db.shape, c.shape, y.shape, b.shape, data_ind.shape)
    print(simulator.rec(y[:,None]))

tf.Tensor([13 14], shape=(2,), dtype=int32) 0 (2,) (2, 78624) (2, 8, 14, 3276) (2, 19464) (2, 78624, 3)
(<tf.Tensor: shape=(2, 1, 19464), dtype=float32, numpy=
array([[[0., 1., 1., ..., 1., 1., 0.]],

       [[1., 1., 0., ..., 1., 1., 1.]]], dtype=float32)>, <tf.Tensor: shape=(2, 1, 1, 78624), dtype=float32, numpy=
array([[[[ 35599.652,  28177.914, -54362.188, ...,  20449.74 ,
           79261.234, -94995.42 ]]],


       [[[-52336.746, -34549.38 ,  76954.39 , ..., -36116.195,
           -9920.474,  15615.282]]]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=bool, numpy=
array([[False],
       [False]])>)
tf.Tensor([16 10], shape=(2,), dtype=int32) 1 (2,) (2, 78624) (2, 8, 14, 3276) (2, 19464) (2, 78624, 3)
(<tf.Tensor: shape=(2, 1, 19464), dtype=float32, numpy=
array([[[0., 0., 0., ..., 1., 0., 0.]],

       [[0., 1., 0., ..., 1., 1., 1.]]], dtype=float32)>, <tf.Tensor: shape=(2, 1, 1, 78624), dtype=float32, numpy=
array([[[[ 31416.582 ,  29704.193 , -74879.555 , ...,    721.2676,
           11909.722 ,  19521.104 ]]],


       [[[  -441.4712, -22842.547 , -19113.12  , ...,  33266.84  ,
           27123.455 ,  22496.697 ]]]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=bool, numpy=
array([[False],
       [False]])>)
tf.Tensor([ 7 15], shape=(2,), dtype=int32) 2 (2,) (2, 78624) (2, 8, 14, 3276) (2, 19464) (2, 78624, 3)
(<tf.Tensor: shape=(2, 1, 19464), dtype=float32, numpy=
array([[[1., 0., 0., ..., 1., 0., 1.]],

       [[0., 1., 1., ..., 0., 1., 1.]]], dtype=float32)>, <tf.Tensor: shape=(2, 1, 1, 78624), dtype=float32, numpy=
array([[[[ 62554.125 , 154647.1   , -62409.055 , ..., -21130.566 ,
          -46273.95  ,  19733.514 ]]],


       [[[-15586.036 ,   2378.363 ,   2062.793 , ...,  -2952.248 ,
            6209.866 ,   -810.7529]]]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=bool, numpy=
array([[False],
       [False]])>)
tf.Tensor([ 6 19], shape=(2,), dtype=int32) 3 (2,) (2, 78624) (2, 8, 14, 3276) (2, 19464) (2, 78624, 3)
(<tf.Tensor: shape=(2, 1, 19464), dtype=float32, numpy=
array([[[1., 1., 1., ..., 1., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.]]], dtype=float32)>, <tf.Tensor: shape=(2, 1, 1, 78624), dtype=float32, numpy=
array([[[[   6980.5996,   10838.75  ,   -5962.4834, ..., -109146.414 ,
           -94082.266 , -103315.2   ]]],


       [[[ 328247.44  ,  -86414.03  ,   66203.42  , ...,  -51303.805 ,
           -93646.86  ,  -18593.2   ]]]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=bool, numpy=
array([[False],
       [False]])>)
tf.Tensor([11 12], shape=(2,), dtype=int32) 4 (2,) (2, 78624) (2, 8, 14, 3276) (2, 19464) (2, 78624, 3)
(<tf.Tensor: shape=(2, 1, 19464), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 1., 1.]],

       [[1., 1., 0., ..., 0., 1., 1.]]], dtype=float32)>, <tf.Tensor: shape=(2, 1, 1, 78624), dtype=float32, numpy=
array([[[[  69205.99 ,  119594.08 ,   39206.47 , ...,   31092.113,
            19423.549,   24195.473]]],


       [[[ -34898.33 , -131983.1  ,  -15638.528, ...,  -13356.301,
            58679.734,  -84301.14 ]]]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=bool, numpy=
array([[False],
       [False]])>)
tf.Tensor([1 9], shape=(2,), dtype=int32) 5 (2,) (2, 78624) (2, 8, 14, 3276) (2, 19464) (2, 78624, 3)
(<tf.Tensor: shape=(2, 1, 19464), dtype=float32, numpy=
array([[[1., 0., 1., ..., 1., 1., 0.]],

       [[1., 0., 0., ..., 1., 0., 1.]]], dtype=float32)>, <tf.Tensor: shape=(2, 1, 1, 78624), dtype=float32, numpy=
array([[[[  29637.34  , -135516.08  ,   -4592.9336, ...,   -8266.639 ,
            26998.262 ,    2545.4365]]],


       [[[ -14872.192 ,   12107.195 ,  -16181.06  , ...,   82084.305 ,
          -109837.22  ,   50854.586 ]]]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=bool, numpy=
array([[False],
       [False]])>)
tf.Tensor([8 2], shape=(2,), dtype=int32) 6 (2,) (2, 78624) (2, 8, 14, 3276) (2, 19464) (2, 78624, 3)
(<tf.Tensor: shape=(2, 1, 19464), dtype=float32, numpy=
array([[[0., 1., 1., ..., 0., 1., 1.]],

       [[0., 0., 0., ..., 0., 1., 1.]]], dtype=float32)>, <tf.Tensor: shape=(2, 1, 1, 78624), dtype=float32, numpy=
array([[[[  6518.626 , -27982.94  ,   9016.535 , ..., 103917.35  ,
          -93325.94  ,  65906.89  ]]],


       [[[ -2118.44  ,  26458.41  , -47016.223 , ...,  -4869.667 ,
            6771.6475, -23514.52  ]]]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=bool, numpy=
array([[False],
       [False]])>)
tf.Tensor([17 18], shape=(2,), dtype=int32) 7 (2,) (2, 78624) (2, 8, 14, 3276) (2, 19464) (2, 78624, 3)
(<tf.Tensor: shape=(2, 1, 19464), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 1., 0.]],

       [[1., 1., 0., ..., 0., 0., 0.]]], dtype=float32)>, <tf.Tensor: shape=(2, 1, 1, 78624), dtype=float32, numpy=
array([[[[  28409.662 ,  -14676.448 ,   37411.926 , ...,   68828.766 ,
            17723.074 ,  105561.88  ]]],


       [[[  -7731.4956,  -40470.06  ,   19690.08  , ..., -156651.05  ,
           -11165.986 ,   47607.805 ]]]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=bool, numpy=
array([[False],
       [False]])>)
tf.Tensor([5 4], shape=(2,), dtype=int32) 8 (2,) (2, 78624) (2, 8, 14, 3276) (2, 19464) (2, 78624, 3)
(<tf.Tensor: shape=(2, 1, 19464), dtype=float32, numpy=
array([[[0., 0., 1., ..., 0., 1., 0.]],

       [[0., 0., 0., ..., 1., 1., 0.]]], dtype=float32)>, <tf.Tensor: shape=(2, 1, 1, 78624), dtype=float32, numpy=
array([[[[ -67857.81 ,  107897.74 ,  -98551.07 , ...,   76695.586,
           -41685.977,  -26469.586]]],


       [[[-139317.9  ,  348287.66 ,   62638.297, ...,  -53700.67 ,
           -41688.938,   25636.531]]]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=bool, numpy=
array([[False],
       [False]])>)
tf.Tensor([0 3], shape=(2,), dtype=int32) 9 (2,) (2, 78624) (2, 8, 14, 3276) (2, 19464) (2, 78624, 3)
(<tf.Tensor: shape=(2, 1, 19464), dtype=float32, numpy=
array([[[1., 0., 0., ..., 1., 1., 0.]],

       [[0., 1., 0., ..., 0., 1., 0.]]], dtype=float32)>, <tf.Tensor: shape=(2, 1, 1, 78624), dtype=float32, numpy=
array([[[[ 64428.92  , -28101.375 ,   4194.33  , ..., -42901.03  ,
           10835.367 , -15682.664 ]]],


       [[[-67520.836 ,  46042.78  ,    755.7451, ..., -44042.58  ,
          -40612.957 ,  45008.03  ]]]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=bool, numpy=
array([[False],
       [False]])>)

In [20]:
from tensorflow.keras.layers import Layer, Conv2D, LayerNormalization, SeparableConv2D
from tensorflow.nn import relu
class ResidualBlock(tf.keras.Model):
    r"""
    This Keras layer implements a convolutional residual block made of two convolutional layers with ReLU activation, layer normalization, and a skip connection.
    The number of convolutional channels of the input must match the number of kernel of the convolutional layers ``num_conv_channel`` for the skip connection to work.

    Input
    ------
    : [batch size, num time samples, num subcarriers, num_conv_channel], tf.float
        Input of the layer

    Output
    -------
    : [batch size, num time samples, num subcarriers, num_conv_channel], tf.float
        Output of the layer
    """

    def build(self, input_shape):

        # Layer normalization is done over the last three dimensions: time, frequency, conv 'channels'
        self._layer_norm_1 = LayerNormalization(axis=(-1, -2, -3))
        self._conv_1 = SeparableConv2D(filters= 64,
                              kernel_size=[3,3],
                              padding='same',
                              activation=None)
        # Layer normalization is done over the last three dimensions: time, frequency, conv 'channels'
        self._layer_norm_2 = LayerNormalization(axis=(-1, -2, -3))
        self._conv_2 = SeparableConv2D(filters= 128,
                              kernel_size=[3,3],
                              padding='same',
                              activation=None)

    def call(self, inputs):
        z = self._layer_norm_1(inputs)
        z = relu(z)
        z = self._conv_1(z)
        z = self._layer_norm_2(z)
        z = relu(z)
        z = self._conv_2(z) # [batch size, num time samples, num subcarriers, num_channels]
        # Skip connection
        z = z + inputs

        return z

class CustomNeuralReceiver(tf.keras.Model):
    r"""
    Keras layer implementing a residual convolutional neural receiver.

    This neural receiver is fed with the post-DFT received samples, forming a resource grid of size num_of_symbols x fft_size, and computes LLRs on the transmitted coded bits.
    These LLRs can then be fed to an outer decoder to reconstruct the information bits.

    Input
    ------
    y_no: [batch size, num ofdm symbols, num subcarriers, 2*num rx antenna + 1], tf.float32
        Concatenated received samples and noise variance.
(
    y : [batch size, num rx antenna, num ofdm symbols, num subcarriers], tf.complex
        Received post-DFT samples.

    no : [batch size], tf.float32
        Noise variance. At training, a different noise variance value is sampled for each batch example.
)
    Output
    -------
    : [batch size, num ofdm symbols, num subcarriers, num_bits_per_symbol]
        LLRs on the transmitted bits.
    """

    def __init__(self, training = False):
        super(CustomNeuralReceiver, self).__init__()
        self._training = training

    def build(self, input_shape):

        # Input convolution
        self._input_conv = Conv2D(filters= 128,
                                  kernel_size=[3,3],
                                  padding='same',
                                  activation=None)
        # Residual blocks
        self._res_block_1 = ResidualBlock()
        self._res_block_2 = ResidualBlock()
        self._res_block_3 = ResidualBlock()
        self._res_block_4 = ResidualBlock()
        # Output conv
        self._output_conv = Conv2D(filters= 2,    # QPSK
                                   kernel_size=[3,3],
                                   padding='same',
                                   activation=None)
        

    @tf.function(jit_compile=True)
    def call(self, inputs):
        # Input conv
        z = self._input_conv(inputs)
        # Residual blocks
        z = self._res_block_1(z)
        z = self._res_block_2(z)
        z = self._res_block_3(z)
        z = self._res_block_4(z)
        # Output conv
        z = self._output_conv(z)
        # if self._training == False:
        #     z = tf.cast(z * (2**7), tf.int8)
        return z
    

_model = CustomNeuralReceiver(training = False)
inputs = tf.zeros([1,3276,14,16])
_model(inputs)
_model.summary()

def load_weights(model, pretrained_weights_path):
    # Build Model with random input
    # Load weights
  with open(pretrained_weights_path, 'rb') as f:
    weights = pickle.load(f)
    model.set_weights(weights)
    print(f"Loaded pretrained weights from {pretrained_weights_path}")

#load_weights(_model, '/content/drive/MyDrive/Pusch_data/Model_weights/model_weight_FULL_RB_epoch_40.pkl')
load_weights(_model, '../model_weight_FULL_RB_epoch_40.pkl')

Model: "custom_neural_receiver_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_2 (Conv2D)           multiple                  18560

 residual_block_4 (Residual  multiple                  17630080
 Block)

 residual_block_5 (Residual  multiple                  17630080
 Block)

 residual_block_6 (Residual  multiple                  17630080
 Block)

 residual_block_7 (Residual  multiple                  17630080
 Block)

 conv2d_3 (Conv2D)           multiple                  2306

=================================================================
Total params: 70541186 (269.09 MB)
Trainable params: 70541186 (269.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Loaded pretrained weights from ../model_weight_FULL_RB_epoch_40.pkl

In [21]:
def loss_cal(pred, label):
  bce = tf.nn.sigmoid_cross_entropy_with_logits(label, pred)
  bce = tf.reduce_mean(bce)
  # rate = tf.constant(1.0, tf.float32) - bce/tf.math.log(2.)
  # loss = -rate
  loss = bce
  return loss

In [22]:
df.iloc[0]

nSFN                                                                        0
nSlot                                                                       4
nPDU                                                                        1
nGroup                                                                      1
nUlsch                                                                      1
nUlcch                                                                      0
nRachPresent                                                                0
nRNTI                                                                   20002
nUEId                                                                       0
nBWPSize                                                                  273
nBWPStart                                                                   0
nSubcSpacing                                                                1
nCpType                                                                     0
nULType                                                                     0
nMcsTable                                                                   0
nMCS                                                                        3
nTransPrecode                                                               0
nTransmissionScheme                                                         0
nNrOfLayers                                                                 1
nPortIndex                                                                [0]
nNid                                                                      246
nSCID                                                                       0
nNIDnSCID                                                                 246
nNrOfAntennaPorts                                                           8
nVRBtoPRB                                                                   0
nPMI                                                                        0
nStartSymbolIndex                                                           0
nNrOfSymbols                                                               14
nResourceAllocType                                                          1
nRBStart                                                                    0
nRBSize                                                                   273
nTBSize                                                                  2433
nRV                                                                         0
nHARQID                                                                     0
nNDI                                                                        1
nMappingType                                                                0
nDMRSConfigType                                                             0
nNrOfCDMs                                                                   2
nNrOfDMRSSymbols                                                            1
nDMRSAddPos                                                                 1
nPTRSPresent                                                                0
nAck                                                                        0
nAlphaScaling                                                               0
nBetaOffsetACKIndex                                                        11
nCsiPart1                                                                   0
nBetaOffsetCsiPart1Index                                                    7
nCsiPart2                                                                   0
nBetaOffsetCsiPart2Index                                                    0
nTpPi2BPSK                                                                  0
nTPPuschID                                                                  0
nRxRUIdx                                             [0, 1, 2, 3, 4, 5, 6, 7]
nUE                                                                         1
nPduIdx                                                                   [0]
Dmrs_mask                   [False, False, False, False, False, False, Fal...
Channel_model                                                    ['CDL', 'A']
Speed                                                                     1.0
Delay_spread                                                            150.0
Esno_db                                                                   3.0
Data_filename                                            20250305063933008560
Data_dirname                                             20250305063919562391
Name: 0, dtype: object

In [23]:
y_ = tf.concat([tf.math.real(y), tf.math.imag(y)], axis=1)
y_ = tf.transpose(y_, perm=[0,3,2,1])
y_

<tf.Tensor: shape=(2, 3276, 14, 16), dtype=float32, numpy=
array([[[[ 3.4856141e-01,  6.7655712e-01,  1.6445942e+00, ...,
          -9.4151247e-01, -9.4782925e-01, -1.6929244e+00],
         [-2.0591171e+00,  9.5540023e-01, -5.9710979e-01, ...,
           1.3324263e+00,  2.1872373e+00,  8.1651664e-01],
         [ 8.7811559e-02,  2.6583752e-01,  1.6383942e+00, ...,
           3.7266903e+00,  2.9546466e+00, -2.6750576e-01],
         ...,
         [ 2.7504539e-01, -1.9469850e+00, -1.3311462e+00, ...,
          -3.5341215e+00, -2.4836531e+00, -4.9577165e-01],
         [ 1.5518521e+00,  2.2954221e+00, -3.7538311e-01, ...,
           4.4959621e+00,  3.2524533e+00, -3.8194728e-01],
         [ 6.0679269e-01,  1.1169598e+00,  1.6175511e-01, ...,
          -2.4763751e+00, -4.5051634e-01, -1.3107517e+00]],

        [[-3.8474259e+00, -3.5440068e+00, -6.1099517e-01, ...,
          -6.7074794e-01,  1.4358218e+00,  3.9118029e-02],
         [ 3.0597975e+00,  2.8747330e+00,  8.2642007e-01, ...,
           1.0761251e+00,  4.0322438e-01,  1.0397748e+00],
         [ 1.9051413e-01, -1.4482207e+00,  5.7404065e-01, ...,
           1.3130170e+00,  3.2305387e-01,  6.0742205e-01],
         ...,
         [-1.8802766e+00, -9.3782443e-01, -2.1042447e+00, ...,
          -2.0044613e+00, -1.3762784e+00,  7.4680674e-01],
         [ 2.4884503e+00,  4.3361483e+00, -2.1204019e+00, ...,
           1.0750921e+00, -5.7668138e-01,  7.5311369e-01],
         [ 2.9525909e+00,  4.5497408e+00,  2.4557528e+00, ...,
          -2.3639607e-01, -4.4852179e-01, -1.6723357e-01]],

        [[ 1.5008043e+00,  2.5377808e+00, -4.4674218e-02, ...,
          -2.1915538e+00, -3.0503936e+00, -3.3966858e+00],
         [-1.6518688e+00,  1.7093369e-01, -1.7590786e+00, ...,
          -2.2649620e+00, -3.9909277e+00, -3.0718865e+00],
         [ 3.4493937e+00, -3.5234606e-01, -3.6277566e+00, ...,
          -3.9393973e+00, -4.2721205e+00, -3.8452497e+00],
         ...,
         [ 4.1578960e+00,  4.1559172e+00,  4.0729151e+00, ...,
           1.9835749e+00,  6.1487228e-01, -1.6297299e+00],
         [-2.4197142e+00, -3.8223209e+00, -3.4351754e+00, ...,
           1.7469926e+00, -1.5005498e+00, -1.3244227e-01],
         [-1.1389091e+00,  4.9051195e-01,  1.1393011e+00, ...,
           2.0650337e+00,  2.0117755e+00,  1.3480136e+00]],

        ...,

        [[ 1.8249512e+00,  3.6395888e+00,  1.5600582e+00, ...,
          -6.9013458e-01, -1.5466882e+00, -2.7233248e+00],
         [ 2.3578672e+00,  2.6059043e+00,  2.3362291e-01, ...,
          -7.9749280e-01, -2.2868633e+00, -2.2761104e+00],
         [ 8.6137509e-01, -5.5359548e-01, -1.7757126e+00, ...,
           5.9495610e-01, -1.9411185e+00,  9.7952050e-01],
         ...,
         [ 2.6323495e+00, -2.9030159e+00,  5.0411904e-01, ...,
          -1.3207185e+00,  1.2251208e+00,  6.9245774e-01],
         [-5.5533814e-01,  2.0927908e+00,  2.1753221e+00, ...,
          -2.8396392e+00, -1.4375559e+00, -4.8447709e+00],
         [ 9.2301852e-01,  1.4685067e+00,  7.9596877e-01, ...,
           1.8167759e+00,  4.1081910e+00,  3.4831867e+00]],

        [[ 2.0890632e+00,  1.2591465e+00,  1.8344891e-01, ...,
           1.3016330e+00,  1.8680401e+00,  2.5321589e+00],
         [-1.1164987e+00,  3.5718769e-01,  1.6229497e+00, ...,
          -1.5785146e+00,  5.6290996e-01,  2.4976373e-01],
         [-2.8485029e+00, -2.7758467e+00, -1.1262286e-01, ...,
          -7.6878393e-01, -2.7635720e+00, -2.5984850e+00],
         ...,
         [ 3.1730187e+00,  3.8778605e+00,  3.2913866e+00, ...,
           5.4565817e-01,  2.2029252e+00,  2.0101089e+00],
         [ 2.9373653e+00,  2.6020603e+00,  1.6795409e-01, ...,
           1.4488835e+00,  3.0346746e+00,  3.3792257e+00],
         [ 2.2279174e+00,  2.3560367e+00, -7.7293098e-01, ...,
          -1.9959825e-01,  1.3168901e+00,  2.8300436e+00]],

        [[ 4.1314893e+00,  4.5344129e+00,  3.8177865e+00, ...,
          -5.9759015e-01, -2.2664797e+00,  2.0679671e-01],
         [ 1.3169096e+00,  1.1007559e+00, -2.3113251e-01, ...,
          -2.2636518e+00, -1.5306392e+00, -6.3408780e-01],
         [ 1.1988945e+00,  2.3629372e-01, -2.0733422e-01, ...,
          -3.9061394e-01, -3.9853591e-01,  1.1508683e+00],
         ...,
         [-3.0204922e-01,  1.5494106e+00, -5.8615094e-01, ...,
           6.9145066e-01,  5.7698482e-01,  3.2185617e-01],
         [-2.0013683e+00, -6.2060022e+00, -1.5709777e+00, ...,
           1.3366184e+00, -2.5649643e-01,  6.2466782e-01],
         [-2.6439581e+00, -5.5870833e+00, -2.2920091e+00, ...,
          -1.3796977e+00,  1.5023872e-01,  1.7741337e+00]]],


       [[[ 1.6713468e+00,  4.0472251e-01, -7.7828145e-01, ...,
          -3.0188727e-01, -2.1361189e+00, -2.5820439e+00],
         [-1.0451523e+00, -3.4495592e-03,  9.8314524e-02, ...,
           2.7689524e+00,  2.2992468e+00,  3.4227469e+00],
         [-4.0929713e+00, -3.1790357e+00, -3.3530765e+00, ...,
          -7.0172489e-01, -9.5936716e-01,  7.6489866e-02],
         ...,
         [ 2.8748288e+00,  4.1723676e+00,  3.0630350e+00, ...,
          -1.7764431e-01,  2.4995205e-01,  8.8823754e-01],
         [ 2.8878984e+00,  3.0994427e+00,  2.5694475e+00, ...,
           6.1988395e-01, -8.9349532e-01, -7.0038843e-01],
         [-2.3411913e+00, -2.2895577e+00, -3.1075749e+00, ...,
          -1.7128832e+00, -9.3154895e-01,  1.3480270e+00]],

        [[ 2.6757438e+00,  3.4032295e+00,  2.6346624e+00, ...,
           3.1732327e-01,  4.0137264e-01,  4.2491388e-01],
         [-8.0144906e-01,  4.7975972e-01,  1.5312490e+00, ...,
           2.6687198e+00,  2.0646257e+00,  8.7193477e-01],
         [ 4.5449069e-01,  5.7693459e-02, -1.5963347e-01, ...,
          -1.2797626e+00,  8.8835001e-02,  3.4144533e-01],
         ...,
         [-5.9875125e-01, -3.6805588e-01, -1.1891714e+00, ...,
          -3.8434356e-01,  1.2032473e+00,  6.4252055e-01],
         [ 1.0535083e+00,  6.5306681e-01, -1.0272880e+00, ...,
          -2.2437294e+00, -1.9661324e+00, -1.7833598e+00],
         [-4.1350374e+00, -2.5789332e+00, -2.5165582e+00, ...,
          -1.8432965e+00, -1.5492251e+00,  1.4761648e+00]],

        [[-1.0249406e+00, -7.0218062e-01, -4.7664458e-01, ...,
           1.1166825e+00, -5.8491337e-01, -8.5308981e-01],
         [ 1.3590283e+00,  2.5740173e+00,  1.0885185e-01, ...,
          -7.1178812e-01, -6.4178908e-01, -1.4439443e-01],
         [ 1.7480345e+00,  1.8202786e+00,  2.2961030e+00, ...,
          -2.7010598e+00, -6.9079024e-01,  5.9807575e-01],
         ...,
         [ 7.0715880e-01,  2.2734120e+00,  1.7242873e+00, ...,
           1.0393629e+00,  3.3394551e-01,  3.7055075e-01],
         [ 9.1046357e-01,  1.5426637e+00,  6.6531312e-01, ...,
           9.3505329e-01, -3.9207911e-01,  8.9541560e-01],
         [-1.7186533e+00, -2.0688367e+00, -8.9168680e-01, ...,
           1.7552149e-01,  1.4326648e+00, -6.5053380e-01]],

        ...,

        [[-1.2164202e+00, -7.8154266e-01, -9.1165677e-04, ...,
           3.9797193e-01,  1.0528879e+00,  3.4914228e-01],
         [-3.6173567e-01, -1.8109934e+00, -1.0509351e+00, ...,
          -2.6425583e+00, -4.4857228e-01, -5.7842493e-01],
         [-2.0046756e-02, -5.8340651e-01, -6.8077296e-01, ...,
          -2.0134097e-01, -4.9383539e-01, -1.0840952e+00],
         ...,
         [-1.1023633e+00, -8.8930868e-02, -1.0519044e-01, ...,
          -5.5751735e-01, -3.5668039e-01, -3.8223085e-01],
         [ 3.8125199e-01,  1.2166795e+00,  1.3606017e+00, ...,
           9.7743487e-01, -3.4031725e-01, -9.3634290e-01],
         [-2.0881798e+00, -4.3207300e-01, -6.9670737e-01, ...,
          -6.2198263e-01,  4.0711516e-01,  8.5351610e-01]],

        [[-2.1388750e+00, -1.2204461e+00, -2.5875890e-01, ...,
          -4.3958381e-01, -3.3236212e-01, -1.2780292e+00],
         [-1.2291913e+00,  1.6059552e-01,  1.7021468e-01, ...,
           1.7471776e+00,  2.5470996e-01, -8.2330734e-01],
         [ 1.6990089e+00,  1.9535587e+00,  1.7211641e+00, ...,
           6.5007967e-01,  4.8488742e-01,  1.0669110e+00],
         ...,
         [-3.3291180e+00, -2.7602935e+00, -1.6233563e-01, ...,
           2.4014258e-01, -1.5400306e+00, -3.0896916e+00],
         [-1.8170216e+00, -1.7347739e+00, -1.1157115e+00, ...,
           1.2847263e-01, -1.5345767e+00, -1.7197539e+00],
         [-5.5410969e-01, -1.0124969e+00,  9.7241187e-01, ...,
           2.1548681e+00, -2.5383496e-01, -1.6820273e-01]],

        [[ 1.9480093e+00,  8.3338225e-01, -1.6089404e+00, ...,
          -2.2583984e-01,  2.2396779e-01,  8.9793050e-01],
         [ 5.1043808e-02, -9.8817295e-01, -1.2548442e+00, ...,
          -2.7448969e+00, -9.5129150e-01,  1.3426310e+00],
         [-7.1001202e-01,  1.9607028e-01,  5.2775788e-01, ...,
           1.9111263e+00,  1.4771249e+00,  2.8992054e-01],
         ...,
         [-6.1151558e-01,  6.4975220e-01, -1.8803261e-01, ...,
           8.0018155e-02,  3.6921892e-01, -4.8379403e-01],
         [-1.8043385e+00, -1.1855900e+00,  5.1466739e-01, ...,
          -4.0789026e-01,  3.5955220e-02, -1.2710312e-01],
         [ 3.0269752e+00, -1.0449719e+00, -3.3477342e-01, ...,
           7.2353846e-01, -5.3664184e-01, -6.3732302e-01]]]],
      dtype=float32)>

In [24]:
pred = _model(y_)
pred = tf.transpose(pred, perm=[0,2,1,3])

In [25]:
pred_ = tf.concat([pred[:,0:2], pred[:,3:11], pred[:,12:14]],axis=-3)
pred_.shape

TensorShape([2, 12, 3276, 2])

In [30]:
c_pred = tf.reshape(pred_, [2,-1])
loss_cal(c_pred, c)

In [27]:
data_ind

<tf.Tensor: shape=(2, 78624, 3), dtype=int32, numpy=
array([[[   0,    0,    0],
        [   0,    0,    1],
        [   0,    1,    0],
        ...,
        [  13, 3274,    1],
        [  13, 3275,    0],
        [  13, 3275,    1]],

       [[   0,    0,    0],
        [   0,    0,    1],
        [   0,    1,    0],
        ...,
        [  13, 3274,    1],
        [  13, 3275,    0],
        [  13, 3275,    1]]], dtype=int32)>

In [28]:
data_extract = tf.gather_nd(pred, data_ind, 1)

In [29]:
loss_cal(data_extract, c)

In [ ]:
# def predict(model, y, data_ind):
#     if len(y.shape) == 5: y = y[:,0]
#     y = tf.transpose(
#             tf.concat([tf.math.real(y), tf.math.imag(y)], axis=1),
#             [0,3,2,1]
#         )
#     pred = model(y)
#     c_soft = tf.gather_nd(tf.transpose(pred, [0, 2, 1, 3]), data_ind, 1)
#     return c_soft, pred
# c_soft, pred = predict(_model, y, data_ind)

In [48]:
loss_cal(c_soft, c)

In [49]:
pred.shape

TensorShape([2, 3276, 14, 2])

In [50]:
_pred = tf.concat([pred[...,0:2,:], pred[...,3:11,:], pred[...,12:14,:]],axis=-2)
_pred.shape

TensorShape([2, 3276, 12, 2])

In [51]:
_pred = tf.transpose(_pred, perm=[0,2,1,3])
_pred

<tf.Tensor: shape=(2, 12, 3276, 2), dtype=float32, numpy=
array([[[[ 1.0469391e+01,  5.0095711e+00],
         [-3.1668515e+00, -5.1410632e+00],
         [-8.6160650e+00, -1.0593261e+01],
         ...,
         [-4.7331257e+00, -9.0367508e-01],
         [ 5.1488929e+00, -8.4180794e+00],
         [ 2.1358950e+00, -1.0051928e-01]],

        [[ 6.4932318e+00,  4.9972405e+00],
         [ 5.7338161e+00,  1.0484211e+01],
         [-3.1574194e+00, -1.1338509e+01],
         ...,
         [-8.5004175e-01,  2.1252000e+00],
         [ 9.0362597e+00,  3.7422626e+00],
         [ 2.0270646e+00,  4.4786558e+00]],

        [[-1.0939690e+01, -9.0610247e+00],
         [ 7.6532638e-01,  3.2562792e+00],
         [-1.8934168e+01,  1.3377622e+00],
         ...,
         [ 1.4547210e+00, -1.9695178e+00],
         [-8.4812746e+00,  9.3804913e+00],
         [-1.0330507e+00,  3.0878043e+00]],

        ...,

        [[ 1.3301461e+01,  4.2935681e+00],
         [ 6.9248252e+00, -9.8991070e+00],
         [-1.1186101e+01,  8.9348106e+00],
         ...,
         [-1.0234448e+01, -2.8379163e-01],
         [ 1.3374128e+01, -8.8196497e+00],
         [ 1.3338661e-02, -4.8915181e+00]],

        [[ 6.7542286e+00, -1.0644134e+01],
         [ 1.1145558e+01, -1.0960773e+01],
         [ 1.0912190e+01,  1.0460262e+01],
         ...,
         [-8.9154568e+00, -8.9197224e-01],
         [-1.6426830e+01,  6.2429194e+00],
         [ 2.1613672e+00,  1.7503272e+00]],

        [[-7.6081181e+00,  7.5580173e+00],
         [-8.3976688e+00, -7.4365096e+00],
         [ 8.2292757e+00,  5.6614366e+00],
         ...,
         [-9.9194109e-01, -4.8791404e+00],
         [-6.4650555e+00, -1.3657995e+00],
         [-1.5788372e+00, -1.6090702e+00]]],


       [[[ 2.4454916e+00, -2.1622282e-01],
         [-3.7511821e+00, -9.4884688e-01],
         [-3.7101681e+00,  2.9696398e+00],
         ...,
         [-1.2596894e+01, -5.7199950e+00],
         [ 6.3710489e+00, -4.5520473e+00],
         [ 1.0347586e+00, -1.1074028e+01]],

        [[ 6.8697977e-01,  5.0457919e-01],
         [ 1.3578221e+00, -4.7429161e+00],
         [ 6.4247918e+00, -1.6462895e+00],
         ...,
         [-5.0358143e+00,  7.7519469e+00],
         [ 1.5854098e+00, -1.6257746e+01],
         [-6.6314049e+00, -3.6556623e+00]],

        [[ 5.6440532e-01,  4.5903678e+00],
         [-2.1748052e+00,  1.3584112e+00],
         [ 1.9511901e+00, -1.0868889e+01],
         ...,
         [-7.4225407e+00,  1.4485232e+00],
         [ 6.8637733e+00,  1.5435110e+01],
         [ 1.2162420e+01,  9.2406406e+00]],

        ...,

        [[ 3.7263315e+00,  7.4841328e+00],
         [-9.0909748e+00, -2.5286074e+00],
         [-7.2775178e+00,  8.2107630e+00],
         ...,
         [ 7.2739248e+00,  1.2884093e+01],
         [ 5.6575680e+00, -9.2768850e+00],
         [-1.0099502e+01, -1.1143654e+01]],

        [[ 8.5373430e+00,  2.3923612e+00],
         [ 5.7195897e+00,  2.3199241e+00],
         [-1.4097872e+01,  2.1036381e+01],
         ...,
         [ 4.0689468e+00,  1.3617950e+01],
         [-1.6850784e+01,  7.4839048e+00],
         [ 8.6456394e+00, -8.5333195e+00]],

        [[-9.5827465e+00,  5.1909719e+00],
         [ 1.0690031e+00, -4.9245024e+00],
         [ 7.8129854e+00,  3.3305514e+00],
         ...,
         [ 7.6192751e+00, -9.8879385e-01],
         [ 1.5804095e+01, -1.4082607e+01],
         [ 8.9288740e+00, -4.1513886e+00]]]], dtype=float32)>

In [52]:
c_pred = tf.reshape(_pred, [2,-1])
loss_cal(c_pred, c)